.486
DATA SEGMENT USE16
SUM DB ?,?
MESG DB '25+9='
	 DB 0,0,'$'
N1 DB 9,0F0H
N2 DW 25
DATA ENDS

CODE SEGMENT USE16
	ASSUME CS:CODE, DS:DATA
BEG:	MOV AX, DATA
		MOV DS, AX
		MOV BX, OFFSET SUM
		MOV AH, N1
		MOV AL, BYTE PTR N2
		ADD AH, AL
		MOV [BX], AH
		CALL CHANG
		MOV AH, 9
		MOV DX, OFFSET MESG
		INT 21H
		MOV AH, 4CH
		INT 21H
CHANG PROC 
LAST:   CMP WORD PTR [BX], 10
		JC NEXT
		SUB WORD PTR [BX], 10
		INC WORD PTR [BX+7]
		JMP LAST
NEXT:   MOV AX, [BX+8]
		ADD AX, WORD PTR SUM
		MOV [BX+8], AX
		MOV AX, [BX+7]
		ADD AX, 30H
		MOV [BX+7], AX
		MOV AX, [BX+8]
		ADD AX, 30H
		MOV [BX+8], AX
		RET
CHANG ENDP
CODE   ENDS
		END BEG
 
